// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, title, description, event_date, event_time, is_completed, created_at, updated_at
FROM calendar_events
WHERE event_date >= $1 AND event_date <= $2
ORDER BY event_date ASC
`

type ListCalendarEventsParams struct {
	EventDate   pgtype.Date `json:"event_date"`
	EventDate_2 pgtype.Date `json:"event_date_2"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents, arg.EventDate, arg.EventDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.EventTime,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
