// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTodayDailyEntry = `-- name: GetTodayDailyEntry :one
SELECT stress_level, video_play_seconds FROM daily_sliders
WHERE user_id = $1 AND created_at >= $2
LIMIT 1
`

type GetTodayDailyEntryParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetTodayDailyEntryRow struct {
	StressLevel      pgtype.Int4 `json:"stress_level"`
	VideoPlaySeconds pgtype.Int4 `json:"video_play_seconds"`
}

func (q *Queries) GetTodayDailyEntry(ctx context.Context, arg GetTodayDailyEntryParams) (GetTodayDailyEntryRow, error) {
	row := q.db.QueryRow(ctx, getTodayDailyEntry, arg.UserID, arg.CreatedAt)
	var i GetTodayDailyEntryRow
	err := row.Scan(&i.StressLevel, &i.VideoPlaySeconds)
	return i, err
}

const getTodayDailyEntryForSubmit = `-- name: GetTodayDailyEntryForSubmit :one
SELECT id, stress_level FROM daily_sliders
WHERE user_id = $1 AND created_at >= $2
LIMIT 1
`

type GetTodayDailyEntryForSubmitParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetTodayDailyEntryForSubmitRow struct {
	ID          int32       `json:"id"`
	StressLevel pgtype.Int4 `json:"stress_level"`
}

func (q *Queries) GetTodayDailyEntryForSubmit(ctx context.Context, arg GetTodayDailyEntryForSubmitParams) (GetTodayDailyEntryForSubmitRow, error) {
	row := q.db.QueryRow(ctx, getTodayDailyEntryForSubmit, arg.UserID, arg.CreatedAt)
	var i GetTodayDailyEntryForSubmitRow
	err := row.Scan(&i.ID, &i.StressLevel)
	return i, err
}

const incrementDailyVideoSeconds = `-- name: IncrementDailyVideoSeconds :one
SELECT id, user_id, mindfulness_practice, practice_duration, practice_location, stress_level, calm_before, calm_after, feelings, sleep_start_time, wake_up_time, sleep_quality, video_play_seconds, created_at, entry_date FROM increment_daily_video_seconds($1, $2)
`

type IncrementDailyVideoSecondsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Seconds int32       `json:"seconds"`
}

// Atomic INSERT ... ON CONFLICT DO UPDATE via the increment_daily_video_seconds
// DB function -- closes the same race as UpsertDailyEntry for these
// frequent video-progress pings.
func (q *Queries) IncrementDailyVideoSeconds(ctx context.Context, arg IncrementDailyVideoSecondsParams) (DailySlider, error) {
	row := q.db.QueryRow(ctx, incrementDailyVideoSeconds, arg.UserID, arg.Seconds)
	var i DailySlider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MindfulnessPractice,
		&i.PracticeDuration,
		&i.PracticeLocation,
		&i.StressLevel,
		&i.CalmBefore,
		&i.CalmAfter,
		&i.Feelings,
		&i.SleepStartTime,
		&i.WakeUpTime,
		&i.SleepQuality,
		&i.VideoPlaySeconds,
		&i.CreatedAt,
		&i.EntryDate,
	)
	return i, err
}

const upsertDailyEntry = `-- name: UpsertDailyEntry :one
INSERT INTO daily_sliders (
    user_id, stress_level, calm_before, calm_after, sleep_quality,
    sleep_start_time, wake_up_time, feelings,
    mindfulness_practice, practice_duration, practice_location
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11
)
ON CONFLICT (user_id, entry_date) DO UPDATE SET
    stress_level = EXCLUDED.stress_level,
    calm_before = EXCLUDED.calm_before,
    calm_after = EXCLUDED.calm_after,
    sleep_quality = EXCLUDED.sleep_quality,
    sleep_start_time = EXCLUDED.sleep_start_time,
    wake_up_time = EXCLUDED.wake_up_time,
    feelings = EXCLUDED.feelings,
    mindfulness_practice = EXCLUDED.mindfulness_practice,
    practice_duration = EXCLUDED.practice_duration,
    practice_location = EXCLUDED.practice_location
RETURNING id, user_id, mindfulness_practice, practice_duration, practice_location, stress_level, calm_before, calm_after, feelings, sleep_start_time, wake_up_time, sleep_quality, video_play_seconds, created_at, entry_date
`

type UpsertDailyEntryParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	StressLevel         pgtype.Int4 `json:"stress_level"`
	CalmBefore          pgtype.Int4 `json:"calm_before"`
	CalmAfter           pgtype.Int4 `json:"calm_after"`
	SleepQuality        pgtype.Int4 `json:"sleep_quality"`
	SleepStartTime      pgtype.Text `json:"sleep_start_time"`
	WakeUpTime          pgtype.Text `json:"wake_up_time"`
	Feelings            pgtype.Text `json:"feelings"`
	MindfulnessPractice pgtype.Text `json:"mindfulness_practice"`
	PracticeDuration    pgtype.Int4 `json:"practice_duration"`
	PracticeLocation    pgtype.Text `json:"practice_location"`
}

// Upsert on (user_id, entry_date) instead of select-then-insert/update --
// closes the double-submit race that would otherwise produce duplicate
// rows for the same day (see project_db.sql's
// daily_sliders_user_entry_date_unique constraint).
func (q *Queries) UpsertDailyEntry(ctx context.Context, arg UpsertDailyEntryParams) (DailySlider, error) {
	row := q.db.QueryRow(ctx, upsertDailyEntry,
		arg.UserID,
		arg.StressLevel,
		arg.CalmBefore,
		arg.CalmAfter,
		arg.SleepQuality,
		arg.SleepStartTime,
		arg.WakeUpTime,
		arg.Feelings,
		arg.MindfulnessPractice,
		arg.PracticeDuration,
		arg.PracticeLocation,
	)
	var i DailySlider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MindfulnessPractice,
		&i.PracticeDuration,
		&i.PracticeLocation,
		&i.StressLevel,
		&i.CalmBefore,
		&i.CalmAfter,
		&i.Feelings,
		&i.SleepStartTime,
		&i.WakeUpTime,
		&i.SleepQuality,
		&i.VideoPlaySeconds,
		&i.CreatedAt,
		&i.EntryDate,
	)
	return i, err
}
