// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDailyEntriesSince = `-- name: CountDailyEntriesSince :one
SELECT COUNT(*) FROM daily_sliders WHERE user_id = $1 AND created_at >= $2
`

type CountDailyEntriesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountDailyEntriesSince(ctx context.Context, arg CountDailyEntriesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyEntriesSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMindfulResponsesSince = `-- name: CountMindfulResponsesSince :one
SELECT COUNT(*) FROM questionnaire_ffmq15_responses WHERE user_id = $1 AND created_at >= $2
`

type CountMindfulResponsesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountMindfulResponsesSince(ctx context.Context, arg CountMindfulResponsesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMindfulResponsesSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStressResponsesSince = `-- name: CountStressResponsesSince :one
SELECT COUNT(*) FROM questionnaire_pss10_responses WHERE user_id = $1 AND created_at >= $2
`

type CountStressResponsesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountStressResponsesSince(ctx context.Context, arg CountStressResponsesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStressResponsesSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThriveResponsesSince = `-- name: CountThriveResponsesSince :one
SELECT COUNT(*) FROM questionnaire_wemwbs14_responses WHERE user_id = $1 AND created_at >= $2
`

type CountThriveResponsesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountThriveResponsesSince(ctx context.Context, arg CountThriveResponsesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countThriveResponsesSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDailyEntriesSince = `-- name: ListDailyEntriesSince :many

SELECT created_at FROM daily_sliders
WHERE user_id = $1 AND created_at >= $2
ORDER BY created_at DESC
`

type ListDailyEntriesSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Queries backing dashboardService.ts's getUserSummary -- see plan §5's
// note that this endpoint deliberately keeps dashboardService.ts's
// server-local-time streak/consistency math as-is (not the SLT-pinned
// helper used everywhere else); that inconsistency is replicated in Go,
// not "fixed", pending a deliberate product/research decision.
func (q *Queries) ListDailyEntriesSince(ctx context.Context, arg ListDailyEntriesSinceParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listDailyEntriesSince, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var created_at pgtype.Timestamptz
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceRecordingsSince = `-- name: ListVoiceRecordingsSince :many
SELECT created_at FROM voice_recordings WHERE user_id = $1 AND created_at >= $2
`

type ListVoiceRecordingsSinceParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVoiceRecordingsSince(ctx context.Context, arg ListVoiceRecordingsSinceParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, listVoiceRecordingsSince, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var created_at pgtype.Timestamptz
		if err := rows.Scan(&created_at); err != nil {
			return nil, err
		}
		items = append(items, created_at)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
