// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journey.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listJourneyDaily = `-- name: ListJourneyDaily :many

SELECT id, user_id, calm_before, calm_after, stress_level, sleep_quality,
       mindfulness_practice, practice_location, feelings, created_at
FROM daily_sliders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJourneyDailyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListJourneyDailyRow struct {
	ID                  int32              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	CalmBefore          pgtype.Int4        `json:"calm_before"`
	CalmAfter           pgtype.Int4        `json:"calm_after"`
	StressLevel         pgtype.Int4        `json:"stress_level"`
	SleepQuality        pgtype.Int4        `json:"sleep_quality"`
	MindfulnessPractice pgtype.Text        `json:"mindfulness_practice"`
	PracticeLocation    pgtype.Text        `json:"practice_location"`
	Feelings            pgtype.Text        `json:"feelings"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// Queries backing journeyController.ts's getJourneyData (GET /api/journey/).
// getJourneyStatus (GET /api/journey/status) has no queries of its own --
// it fans out to each feature domain's own status query (daily.sql,
// weekly.sql, thrive.sql, stress.sql, mindful.sql).
func (q *Queries) ListJourneyDaily(ctx context.Context, arg ListJourneyDailyParams) ([]ListJourneyDailyRow, error) {
	rows, err := q.db.Query(ctx, listJourneyDaily, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneyDailyRow
	for rows.Next() {
		var i ListJourneyDailyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CalmBefore,
			&i.CalmAfter,
			&i.StressLevel,
			&i.SleepQuality,
			&i.MindfulnessPractice,
			&i.PracticeLocation,
			&i.Feelings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneyMindful = `-- name: ListJourneyMindful :many
SELECT id, created_at FROM questionnaire_ffmq15_responses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJourneyMindfulParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListJourneyMindfulRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListJourneyMindful(ctx context.Context, arg ListJourneyMindfulParams) ([]ListJourneyMindfulRow, error) {
	rows, err := q.db.Query(ctx, listJourneyMindful, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneyMindfulRow
	for rows.Next() {
		var i ListJourneyMindfulRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneyStress = `-- name: ListJourneyStress :many
SELECT id, created_at FROM questionnaire_pss10_responses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJourneyStressParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListJourneyStressRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListJourneyStress(ctx context.Context, arg ListJourneyStressParams) ([]ListJourneyStressRow, error) {
	rows, err := q.db.Query(ctx, listJourneyStress, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneyStressRow
	for rows.Next() {
		var i ListJourneyStressRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneyThrive = `-- name: ListJourneyThrive :many
SELECT id, created_at FROM questionnaire_wemwbs14_responses
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJourneyThriveParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListJourneyThriveRow struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListJourneyThrive(ctx context.Context, arg ListJourneyThriveParams) ([]ListJourneyThriveRow, error) {
	rows, err := q.db.Query(ctx, listJourneyThrive, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneyThriveRow
	for rows.Next() {
		var i ListJourneyThriveRow
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJourneyWeekly = `-- name: ListJourneyWeekly :many
SELECT id, user_id, week_number, year, file_url, duration, created_at
FROM voice_recordings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJourneyWeeklyParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListJourneyWeeklyRow struct {
	ID         int32              `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	WeekNumber int32              `json:"week_number"`
	Year       int32              `json:"year"`
	FileUrl    pgtype.Text        `json:"file_url"`
	Duration   pgtype.Int4        `json:"duration"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListJourneyWeekly(ctx context.Context, arg ListJourneyWeeklyParams) ([]ListJourneyWeeklyRow, error) {
	rows, err := q.db.Query(ctx, listJourneyWeekly, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneyWeeklyRow
	for rows.Next() {
		var i ListJourneyWeeklyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeekNumber,
			&i.Year,
			&i.FileUrl,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
