// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mindful.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestMindfulResponse = `-- name: GetLatestMindfulResponse :one
SELECT created_at FROM questionnaire_ffmq15_responses
WHERE user_id = $1 AND created_at >= $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestMindfulResponseParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestMindfulResponse(ctx context.Context, arg GetLatestMindfulResponseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestMindfulResponse, arg.UserID, arg.CreatedAt)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const submitMindfulEntry = `-- name: SubmitMindfulEntry :one
SELECT id, user_id, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12, q13, q14, q15, duration, observing_score, describing_score, awareness_score, non_judging_score, non_reactivity_score, created_at FROM submit_mindful_entry(
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22
)
`

type SubmitMindfulEntryParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Q1                 int32       `json:"q1"`
	Q2                 int32       `json:"q2"`
	Q3                 int32       `json:"q3"`
	Q4                 int32       `json:"q4"`
	Q5                 int32       `json:"q5"`
	Q6                 int32       `json:"q6"`
	Q7                 int32       `json:"q7"`
	Q8                 int32       `json:"q8"`
	Q9                 int32       `json:"q9"`
	Q10                int32       `json:"q10"`
	Q11                int32       `json:"q11"`
	Q12                int32       `json:"q12"`
	Q13                int32       `json:"q13"`
	Q14                int32       `json:"q14"`
	Q15                int32       `json:"q15"`
	ObservingScore     int32       `json:"observing_score"`
	DescribingScore    int32       `json:"describing_score"`
	AwarenessScore     int32       `json:"awareness_score"`
	NonJudgingScore    int32       `json:"non_judging_score"`
	NonReactivityScore int32       `json:"non_reactivity_score"`
	Duration           pgtype.Int4 `json:"duration"`
}

// Rolling 30-day lockout, advisory-lock-enforced RPC -- see thrive.sql's
// SubmitThriveEntry comment / plan §3 for why. Facet scores are computed
// in Go (services/mindful.go) before this call, never in SQL -- see
// CLAUDE.md/plan §5's FFMQ-15 facet-scoring note.
func (q *Queries) SubmitMindfulEntry(ctx context.Context, arg SubmitMindfulEntryParams) (QuestionnaireFfmq15Response, error) {
	row := q.db.QueryRow(ctx, submitMindfulEntry,
		arg.UserID,
		arg.Q1,
		arg.Q2,
		arg.Q3,
		arg.Q4,
		arg.Q5,
		arg.Q6,
		arg.Q7,
		arg.Q8,
		arg.Q9,
		arg.Q10,
		arg.Q11,
		arg.Q12,
		arg.Q13,
		arg.Q14,
		arg.Q15,
		arg.ObservingScore,
		arg.DescribingScore,
		arg.AwarenessScore,
		arg.NonJudgingScore,
		arg.NonReactivityScore,
		arg.Duration,
	)
	var i QuestionnaireFfmq15Response
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Q1,
		&i.Q2,
		&i.Q3,
		&i.Q4,
		&i.Q5,
		&i.Q6,
		&i.Q7,
		&i.Q8,
		&i.Q9,
		&i.Q10,
		&i.Q11,
		&i.Q12,
		&i.Q13,
		&i.Q14,
		&i.Q15,
		&i.Duration,
		&i.ObservingScore,
		&i.DescribingScore,
		&i.AwarenessScore,
		&i.NonJudgingScore,
		&i.NonReactivityScore,
		&i.CreatedAt,
	)
	return i, err
}
