// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AboutMeProfile struct {
	ID                 pgtype.UUID        `json:"id"`
	UniversityID       pgtype.Text        `json:"university_id"`
	EducationLevel     pgtype.Text        `json:"education_level"`
	Faculty            pgtype.Text        `json:"faculty"`
	MajorFieldOfStudy  pgtype.Text        `json:"major_field_of_study"`
	Age                pgtype.Int4        `json:"age"`
	LivingSituation    pgtype.Text        `json:"living_situation"`
	FamilyBackground   pgtype.Text        `json:"family_background"`
	CulturalBackground pgtype.Text        `json:"cultural_background"`
	HobbiesInterests   pgtype.Text        `json:"hobbies_interests"`
	PersonalGoals      pgtype.Text        `json:"personal_goals"`
	WhyMindflow        pgtype.Text        `json:"why_mindflow"`
	IsCompleted        pgtype.Bool        `json:"is_completed"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Admin struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

type CalendarEvent struct {
	ID          int32              `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EventDate   pgtype.Date        `json:"event_date"`
	EventTime   pgtype.Time        `json:"event_time"`
	IsCompleted pgtype.Bool        `json:"is_completed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DailySlider struct {
	ID                  int32              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	MindfulnessPractice pgtype.Text        `json:"mindfulness_practice"`
	PracticeDuration    pgtype.Int4        `json:"practice_duration"`
	PracticeLocation    pgtype.Text        `json:"practice_location"`
	StressLevel         pgtype.Int4        `json:"stress_level"`
	CalmBefore          pgtype.Int4        `json:"calm_before"`
	CalmAfter           pgtype.Int4        `json:"calm_after"`
	Feelings            pgtype.Text        `json:"feelings"`
	SleepStartTime      pgtype.Text        `json:"sleep_start_time"`
	WakeUpTime          pgtype.Text        `json:"wake_up_time"`
	SleepQuality        pgtype.Int4        `json:"sleep_quality"`
	VideoPlaySeconds    pgtype.Int4        `json:"video_play_seconds"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	EntryDate           pgtype.Date        `json:"entry_date"`
}

type Profile struct {
	ID         pgtype.UUID        `json:"id"`
	Username   pgtype.Text        `json:"username"`
	ResearchID pgtype.Text        `json:"research_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PushToken struct {
	ID            int32              `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ExpoPushToken string             `json:"expo_push_token"`
	Platform      pgtype.Text        `json:"platform"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type QuestionnaireFfmq15Response struct {
	ID                 int32              `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Q1                 int32              `json:"q1"`
	Q2                 int32              `json:"q2"`
	Q3                 int32              `json:"q3"`
	Q4                 int32              `json:"q4"`
	Q5                 int32              `json:"q5"`
	Q6                 int32              `json:"q6"`
	Q7                 int32              `json:"q7"`
	Q8                 int32              `json:"q8"`
	Q9                 int32              `json:"q9"`
	Q10                int32              `json:"q10"`
	Q11                int32              `json:"q11"`
	Q12                int32              `json:"q12"`
	Q13                int32              `json:"q13"`
	Q14                int32              `json:"q14"`
	Q15                int32              `json:"q15"`
	Duration           pgtype.Int4        `json:"duration"`
	ObservingScore     pgtype.Int4        `json:"observing_score"`
	DescribingScore    pgtype.Int4        `json:"describing_score"`
	AwarenessScore     pgtype.Int4        `json:"awareness_score"`
	NonJudgingScore    pgtype.Int4        `json:"non_judging_score"`
	NonReactivityScore pgtype.Int4        `json:"non_reactivity_score"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type QuestionnairePss10Response struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Q1        int32              `json:"q1"`
	Q2        int32              `json:"q2"`
	Q3        int32              `json:"q3"`
	Q4        int32              `json:"q4"`
	Q5        int32              `json:"q5"`
	Q6        int32              `json:"q6"`
	Q7        int32              `json:"q7"`
	Q8        int32              `json:"q8"`
	Q9        int32              `json:"q9"`
	Q10       int32              `json:"q10"`
	Duration  pgtype.Int4        `json:"duration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QuestionnaireWemwbs14Response struct {
	ID        int32              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Q1        int32              `json:"q1"`
	Q2        int32              `json:"q2"`
	Q3        int32              `json:"q3"`
	Q4        int32              `json:"q4"`
	Q5        int32              `json:"q5"`
	Q6        int32              `json:"q6"`
	Q7        int32              `json:"q7"`
	Q8        int32              `json:"q8"`
	Q9        int32              `json:"q9"`
	Q10       int32              `json:"q10"`
	Q11       int32              `json:"q11"`
	Q12       int32              `json:"q12"`
	Q13       int32              `json:"q13"`
	Q14       int32              `json:"q14"`
	Duration  pgtype.Int4        `json:"duration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VoiceRecording struct {
	ID         int32              `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	WeekNumber int32              `json:"week_number"`
	Year       int32              `json:"year"`
	FileKey    string             `json:"file_key"`
	FileUrl    pgtype.Text        `json:"file_url"`
	Duration   pgtype.Int4        `json:"duration"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type WeeklyRecording struct {
	ID          int32              `json:"id"`
	WeekNo      int32              `json:"week_no"`
	Title       string             `json:"title"`
	YoutubeID   string             `json:"youtube_id"`
	Description pgtype.Text        `json:"description"`
	TargetGroup pgtype.Text        `json:"target_group"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
