// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE expo_push_token = $1 AND user_id = $2
`

type DeletePushTokenParams struct {
	ExpoPushToken string      `json:"expo_push_token"`
	UserID        pgtype.UUID `json:"user_id"`
}

// Scoped to both expo_push_token AND user_id together -- a security
// property (prevents unregistering another user's device via a leaked/
// guessed token), not an incidental query shape. See plan §5.
func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.ExpoPushToken, arg.UserID)
	return err
}

const listAllPushTokens = `-- name: ListAllPushTokens :many
SELECT user_id, expo_push_token FROM push_tokens
`

type ListAllPushTokensRow struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpoPushToken string      `json:"expo_push_token"`
}

func (q *Queries) ListAllPushTokens(ctx context.Context) ([]ListAllPushTokensRow, error) {
	rows, err := q.db.Query(ctx, listAllPushTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPushTokensRow
	for rows.Next() {
		var i ListAllPushTokensRow
		if err := rows.Scan(&i.UserID, &i.ExpoPushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileUsernamesByID = `-- name: ListProfileUsernamesByID :many
SELECT id, username FROM profiles WHERE id = ANY($1::uuid[])
`

type ListProfileUsernamesByIDRow struct {
	ID       pgtype.UUID `json:"id"`
	Username pgtype.Text `json:"username"`
}

func (q *Queries) ListProfileUsernamesByID(ctx context.Context, ids []pgtype.UUID) ([]ListProfileUsernamesByIDRow, error) {
	rows, err := q.db.Query(ctx, listProfileUsernamesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileUsernamesByIDRow
	for rows.Next() {
		var i ListProfileUsernamesByIDRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushToken = `-- name: UpsertPushToken :exec
INSERT INTO push_tokens (user_id, expo_push_token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (expo_push_token) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform
`

type UpsertPushTokenParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ExpoPushToken string      `json:"expo_push_token"`
	Platform      pgtype.Text `json:"platform"`
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPushToken, arg.UserID, arg.ExpoPushToken, arg.Platform)
	return err
}
