// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAboutMe = `-- name: GetAboutMe :one
SELECT id, university_id, education_level, faculty, major_field_of_study, age, living_situation, family_background, cultural_background, hobbies_interests, personal_goals, why_mindflow, is_completed, created_at, updated_at FROM about_me_profiles WHERE id = $1
`

func (q *Queries) GetAboutMe(ctx context.Context, id pgtype.UUID) (AboutMeProfile, error) {
	row := q.db.QueryRow(ctx, getAboutMe, id)
	var i AboutMeProfile
	err := row.Scan(
		&i.ID,
		&i.UniversityID,
		&i.EducationLevel,
		&i.Faculty,
		&i.MajorFieldOfStudy,
		&i.Age,
		&i.LivingSituation,
		&i.FamilyBackground,
		&i.CulturalBackground,
		&i.HobbiesInterests,
		&i.PersonalGoals,
		&i.WhyMindflow,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT username, research_id FROM profiles WHERE id = $1
`

type GetProfileRow struct {
	Username   pgtype.Text `json:"username"`
	ResearchID pgtype.Text `json:"research_id"`
}

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(&i.Username, &i.ResearchID)
	return i, err
}

const getResearchID = `-- name: GetResearchID :one
SELECT research_id FROM profiles WHERE id = $1
`

func (q *Queries) GetResearchID(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getResearchID, id)
	var research_id pgtype.Text
	err := row.Scan(&research_id)
	return research_id, err
}

const upsertProfileUsername = `-- name: UpsertProfileUsername :exec

INSERT INTO profiles (id, username) VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username
`

type UpsertProfileUsernameParams struct {
	ID       pgtype.UUID `json:"id"`
	Username pgtype.Text `json:"username"`
}

// POST /api/profile/about-me (updateAboutMe) is a write endpoint, out of
// scope for the read-only phase-2 pass -- see plan §2. Its partial-upsert
// semantics (only fields present in the request body get overwritten,
// everything else keeps its previous value) don't map onto a single
// fixed-column sqlc query anyway; it needs a dynamically built UPDATE SET
// clause, ported when the write endpoints land.
// Signup's initial username assignment. Only touches username -- never
// research_id (that's researcher-assigned only, never set at signup --
// see CLAUDE.md's research-group note). A collision with another user's
// username surfaces as a unique_violation (SQLSTATE 23505) on the
// profiles_username_key constraint, which authController.ts's caller
// catches to retry once with an id-suffixed username.
func (q *Queries) UpsertProfileUsername(ctx context.Context, arg UpsertProfileUsernameParams) error {
	_, err := q.db.Exec(ctx, upsertProfileUsername, arg.ID, arg.Username)
	return err
}
