// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDailyEntriesSince(ctx context.Context, arg CountDailyEntriesSinceParams) (int64, error)
	CountMindfulResponsesSince(ctx context.Context, arg CountMindfulResponsesSinceParams) (int64, error)
	CountStressResponsesSince(ctx context.Context, arg CountStressResponsesSinceParams) (int64, error)
	CountThriveResponsesSince(ctx context.Context, arg CountThriveResponsesSinceParams) (int64, error)
	// Scoped to both expo_push_token AND user_id together -- a security
	// property (prevents unregistering another user's device via a leaked/
	// guessed token), not an incidental query shape. See plan §5.
	DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error
	GetAboutMe(ctx context.Context, id pgtype.UUID) (AboutMeProfile, error)
	GetLatestMindfulResponse(ctx context.Context, arg GetLatestMindfulResponseParams) (pgtype.Timestamptz, error)
	GetLatestStressResponse(ctx context.Context, arg GetLatestStressResponseParams) (pgtype.Timestamptz, error)
	GetLatestThriveResponse(ctx context.Context, arg GetLatestThriveResponseParams) (pgtype.Timestamptz, error)
	GetProfile(ctx context.Context, id pgtype.UUID) (GetProfileRow, error)
	GetResearchID(ctx context.Context, id pgtype.UUID) (pgtype.Text, error)
	GetTodayDailyEntry(ctx context.Context, arg GetTodayDailyEntryParams) (GetTodayDailyEntryRow, error)
	GetTodayDailyEntryForSubmit(ctx context.Context, arg GetTodayDailyEntryForSubmitParams) (GetTodayDailyEntryForSubmitRow, error)
	GetWeeklyRecordingForWeek(ctx context.Context, arg GetWeeklyRecordingForWeekParams) (int32, error)
	// Atomic INSERT ... ON CONFLICT DO UPDATE via the increment_daily_video_seconds
	// DB function -- closes the same race as UpsertDailyEntry for these
	// frequent video-progress pings.
	IncrementDailyVideoSeconds(ctx context.Context, arg IncrementDailyVideoSecondsParams) (DailySlider, error)
	ListAllPushTokens(ctx context.Context) ([]ListAllPushTokensRow, error)
	ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error)
	// Queries backing dashboardService.ts's getUserSummary -- see plan §5's
	// note that this endpoint deliberately keeps dashboardService.ts's
	// server-local-time streak/consistency math as-is (not the SLT-pinned
	// helper used everywhere else); that inconsistency is replicated in Go,
	// not "fixed", pending a deliberate product/research decision.
	ListDailyEntriesSince(ctx context.Context, arg ListDailyEntriesSinceParams) ([]pgtype.Timestamptz, error)
	// Queries backing journeyController.ts's getJourneyData (GET /api/journey/).
	// getJourneyStatus (GET /api/journey/status) has no queries of its own --
	// it fans out to each feature domain's own status query (daily.sql,
	// weekly.sql, thrive.sql, stress.sql, mindful.sql).
	ListJourneyDaily(ctx context.Context, arg ListJourneyDailyParams) ([]ListJourneyDailyRow, error)
	ListJourneyMindful(ctx context.Context, arg ListJourneyMindfulParams) ([]ListJourneyMindfulRow, error)
	ListJourneyStress(ctx context.Context, arg ListJourneyStressParams) ([]ListJourneyStressRow, error)
	ListJourneyThrive(ctx context.Context, arg ListJourneyThriveParams) ([]ListJourneyThriveRow, error)
	ListJourneyWeekly(ctx context.Context, arg ListJourneyWeeklyParams) ([]ListJourneyWeeklyRow, error)
	ListProfileUsernamesByID(ctx context.Context, ids []pgtype.UUID) ([]ListProfileUsernamesByIDRow, error)
	ListVoiceRecordingsSince(ctx context.Context, arg ListVoiceRecordingsSinceParams) ([]pgtype.Timestamptz, error)
	// Ordered so the caller (getWeeklyVideo) can prefer the most recently
	// published match; group vs. group-agnostic selection happens in Go.
	ListWeeklyRecordingsForWeek(ctx context.Context, weekNo int32) ([]WeeklyRecording, error)
	// Rolling 30-day lockout, advisory-lock-enforced RPC -- see thrive.sql's
	// SubmitThriveEntry comment / plan §3 for why. Facet scores are computed
	// in Go (services/mindful.go) before this call, never in SQL -- see
	// CLAUDE.md/plan §5's FFMQ-15 facet-scoring note.
	SubmitMindfulEntry(ctx context.Context, arg SubmitMindfulEntryParams) (QuestionnaireFfmq15Response, error)
	// Rolling 30-day lockout, advisory-lock-enforced RPC -- see thrive.sql's
	// SubmitThriveEntry comment / plan §3 for why.
	SubmitStressEntry(ctx context.Context, arg SubmitStressEntryParams) (QuestionnairePss10Response, error)
	// Rolling 14-day lockout has no fixed period to key a UNIQUE constraint
	// on, so submit_thrive_entry (project_db.sql) enforces it atomically via
	// a per-user Postgres advisory lock instead -- reused as-is via this RPC
	// call, zero reimplementation risk (see plan §3). Raises
	// THRIVE_ALREADY_SUBMITTED, caught by the caller via *pgconn.PgError.
	SubmitThriveEntry(ctx context.Context, arg SubmitThriveEntryParams) (QuestionnaireWemwbs14Response, error)
	// Upsert on (user_id, entry_date) instead of select-then-insert/update --
	// closes the double-submit race that would otherwise produce duplicate
	// rows for the same day (see project_db.sql's
	// daily_sliders_user_entry_date_unique constraint).
	UpsertDailyEntry(ctx context.Context, arg UpsertDailyEntryParams) (DailySlider, error)
	// POST /api/profile/about-me (updateAboutMe) is a write endpoint, out of
	// scope for the read-only phase-2 pass -- see plan §2. Its partial-upsert
	// semantics (only fields present in the request body get overwritten,
	// everything else keeps its previous value) don't map onto a single
	// fixed-column sqlc query anyway; it needs a dynamically built UPDATE SET
	// clause, ported when the write endpoints land.
	// Signup's initial username assignment. Only touches username -- never
	// research_id (that's researcher-assigned only, never set at signup --
	// see CLAUDE.md's research-group note). A collision with another user's
	// username surfaces as a unique_violation (SQLSTATE 23505) on the
	// profiles_username_key constraint, which authController.ts's caller
	// catches to retry once with an id-suffixed username.
	UpsertProfileUsername(ctx context.Context, arg UpsertProfileUsernameParams) error
	UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error
	// Upsert on (user_id, week_number, year) instead of a plain insert --
	// closes the double-submit race and lets a legitimate re-submit update
	// the existing row (see project_db.sql's
	// voice_recordings_user_week_year_unique constraint).
	UpsertVoiceRecording(ctx context.Context, arg UpsertVoiceRecordingParams) (VoiceRecording, error)
}

var _ Querier = (*Queries)(nil)
