// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stress.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestStressResponse = `-- name: GetLatestStressResponse :one
SELECT created_at FROM questionnaire_pss10_responses
WHERE user_id = $1 AND created_at >= $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestStressResponseParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestStressResponse(ctx context.Context, arg GetLatestStressResponseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestStressResponse, arg.UserID, arg.CreatedAt)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const submitStressEntry = `-- name: SubmitStressEntry :one
SELECT id, user_id, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, duration, created_at FROM submit_stress_entry(
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12
)
`

type SubmitStressEntryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Q1       int32       `json:"q1"`
	Q2       int32       `json:"q2"`
	Q3       int32       `json:"q3"`
	Q4       int32       `json:"q4"`
	Q5       int32       `json:"q5"`
	Q6       int32       `json:"q6"`
	Q7       int32       `json:"q7"`
	Q8       int32       `json:"q8"`
	Q9       int32       `json:"q9"`
	Q10      int32       `json:"q10"`
	Duration pgtype.Int4 `json:"duration"`
}

// Rolling 30-day lockout, advisory-lock-enforced RPC -- see thrive.sql's
// SubmitThriveEntry comment / plan §3 for why.
func (q *Queries) SubmitStressEntry(ctx context.Context, arg SubmitStressEntryParams) (QuestionnairePss10Response, error) {
	row := q.db.QueryRow(ctx, submitStressEntry,
		arg.UserID,
		arg.Q1,
		arg.Q2,
		arg.Q3,
		arg.Q4,
		arg.Q5,
		arg.Q6,
		arg.Q7,
		arg.Q8,
		arg.Q9,
		arg.Q10,
		arg.Duration,
	)
	var i QuestionnairePss10Response
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Q1,
		&i.Q2,
		&i.Q3,
		&i.Q4,
		&i.Q5,
		&i.Q6,
		&i.Q7,
		&i.Q8,
		&i.Q9,
		&i.Q10,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}
