// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thrive.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestThriveResponse = `-- name: GetLatestThriveResponse :one
SELECT created_at FROM questionnaire_wemwbs14_responses
WHERE user_id = $1 AND created_at >= $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestThriveResponseParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestThriveResponse(ctx context.Context, arg GetLatestThriveResponseParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestThriveResponse, arg.UserID, arg.CreatedAt)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const submitThriveEntry = `-- name: SubmitThriveEntry :one
SELECT id, user_id, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12, q13, q14, duration, created_at FROM submit_thrive_entry(
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
`

type SubmitThriveEntryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Q1       int32       `json:"q1"`
	Q2       int32       `json:"q2"`
	Q3       int32       `json:"q3"`
	Q4       int32       `json:"q4"`
	Q5       int32       `json:"q5"`
	Q6       int32       `json:"q6"`
	Q7       int32       `json:"q7"`
	Q8       int32       `json:"q8"`
	Q9       int32       `json:"q9"`
	Q10      int32       `json:"q10"`
	Q11      int32       `json:"q11"`
	Q12      int32       `json:"q12"`
	Q13      int32       `json:"q13"`
	Q14      int32       `json:"q14"`
	Duration pgtype.Int4 `json:"duration"`
}

// Rolling 14-day lockout has no fixed period to key a UNIQUE constraint
// on, so submit_thrive_entry (project_db.sql) enforces it atomically via
// a per-user Postgres advisory lock instead -- reused as-is via this RPC
// call, zero reimplementation risk (see plan §3). Raises
// THRIVE_ALREADY_SUBMITTED, caught by the caller via *pgconn.PgError.
func (q *Queries) SubmitThriveEntry(ctx context.Context, arg SubmitThriveEntryParams) (QuestionnaireWemwbs14Response, error) {
	row := q.db.QueryRow(ctx, submitThriveEntry,
		arg.UserID,
		arg.Q1,
		arg.Q2,
		arg.Q3,
		arg.Q4,
		arg.Q5,
		arg.Q6,
		arg.Q7,
		arg.Q8,
		arg.Q9,
		arg.Q10,
		arg.Q11,
		arg.Q12,
		arg.Q13,
		arg.Q14,
		arg.Duration,
	)
	var i QuestionnaireWemwbs14Response
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Q1,
		&i.Q2,
		&i.Q3,
		&i.Q4,
		&i.Q5,
		&i.Q6,
		&i.Q7,
		&i.Q8,
		&i.Q9,
		&i.Q10,
		&i.Q11,
		&i.Q12,
		&i.Q13,
		&i.Q14,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}
