// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWeeklyRecordingForWeek = `-- name: GetWeeklyRecordingForWeek :one
SELECT id FROM voice_recordings
WHERE user_id = $1 AND week_number = $2 AND year = $3
LIMIT 1
`

type GetWeeklyRecordingForWeekParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	WeekNumber int32       `json:"week_number"`
	Year       int32       `json:"year"`
}

func (q *Queries) GetWeeklyRecordingForWeek(ctx context.Context, arg GetWeeklyRecordingForWeekParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWeeklyRecordingForWeek, arg.UserID, arg.WeekNumber, arg.Year)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listWeeklyRecordingsForWeek = `-- name: ListWeeklyRecordingsForWeek :many
SELECT id, week_no, title, youtube_id, description, target_group, published_at, created_at FROM weekly_recordings
WHERE week_no = $1
ORDER BY published_at DESC
`

// Ordered so the caller (getWeeklyVideo) can prefer the most recently
// published match; group vs. group-agnostic selection happens in Go.
func (q *Queries) ListWeeklyRecordingsForWeek(ctx context.Context, weekNo int32) ([]WeeklyRecording, error) {
	rows, err := q.db.Query(ctx, listWeeklyRecordingsForWeek, weekNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyRecording
	for rows.Next() {
		var i WeeklyRecording
		if err := rows.Scan(
			&i.ID,
			&i.WeekNo,
			&i.Title,
			&i.YoutubeID,
			&i.Description,
			&i.TargetGroup,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVoiceRecording = `-- name: UpsertVoiceRecording :one
INSERT INTO voice_recordings (user_id, week_number, year, file_url, file_key, duration)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, week_number, year) DO UPDATE SET
    file_url = EXCLUDED.file_url,
    file_key = EXCLUDED.file_key,
    duration = EXCLUDED.duration
RETURNING id, user_id, week_number, year, file_key, file_url, duration, created_at, updated_at
`

type UpsertVoiceRecordingParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	WeekNumber int32       `json:"week_number"`
	Year       int32       `json:"year"`
	FileUrl    pgtype.Text `json:"file_url"`
	FileKey    string      `json:"file_key"`
	Duration   pgtype.Int4 `json:"duration"`
}

// Upsert on (user_id, week_number, year) instead of a plain insert --
// closes the double-submit race and lets a legitimate re-submit update
// the existing row (see project_db.sql's
// voice_recordings_user_week_year_unique constraint).
func (q *Queries) UpsertVoiceRecording(ctx context.Context, arg UpsertVoiceRecordingParams) (VoiceRecording, error) {
	row := q.db.QueryRow(ctx, upsertVoiceRecording,
		arg.UserID,
		arg.WeekNumber,
		arg.Year,
		arg.FileUrl,
		arg.FileKey,
		arg.Duration,
	)
	var i VoiceRecording
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekNumber,
		&i.Year,
		&i.FileKey,
		&i.FileUrl,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
